version: '3.4'

services:
  app:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    ports:
        - "50000:50000"
    networks:
      - app_net
    depends_on:
      - db
  db:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
      ports:
        - "27017:27017"
      networks:
        - app_net
      logging:
        driver: none
networks:
  app_net:
    driver: bridge
